<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Application" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Zahy.Identity.Domain\Zahy.Identity.Domain.csproj" />
    <ProjectReference Include="..\Zahy.Identity.Application.Contracts\Zahy.Identity.Application.Contracts.csproj" />
  </ItemGroup>
</Project>