<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Application" />
    <PackageReference Include="Volo.Abp.Authorization" />
    <PackageReference Include="QuestPDF" />
    <PackageReference Include="ClosedXML" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Zahy.Finance.Domain\Zahy.Finance.Domain.csproj" />
    <ProjectReference Include="..\Zahy.Finance.Application.Contracts\Zahy.Finance.Application.Contracts.csproj" />
    <ProjectReference Include="..\..\Zahy.Commission\Zahy.Commission.Application.Contracts\Zahy.Commission.Application.Contracts.csproj" />
    <ProjectReference Include="..\..\Zahy.Commission\Zahy.Commission.Application\Zahy.Commission.Application.csproj" />
    <ProjectReference Include="..\..\Zahy.Identity\Zahy.Identity.Domain\Zahy.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\Zahy.PartnerPlatform\Zahy.PartnerPlatform.Domain\Zahy.PartnerPlatform.Domain.csproj" />
    <ProjectReference Include="..\..\Zahy.PartnerCatalog\Zahy.PartnerCatalog.Domain\Zahy.PartnerCatalog.Domain.csproj" />
  </ItemGroup>
</Project>
