<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Application" />
    <PackageReference Include="Volo.Abp.Authorization" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Zahy.PartnerCatalog.Domain\Zahy.PartnerCatalog.Domain.csproj" />
    <ProjectReference Include="..\Zahy.PartnerCatalog.Application.Contracts\Zahy.PartnerCatalog.Application.Contracts.csproj" />
    <ProjectReference Include="..\..\Zahy.Identity\Zahy.Identity.Domain\Zahy.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\Zahy.Identity\Zahy.Identity.Domain.Shared\Zahy.Identity.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\Zahy.Settlement\Zahy.Settlement.Application\Zahy.Settlement.Application.csproj" />
    <ProjectReference Include="..\..\Zahy.Settlement\Zahy.Settlement.Application.Contracts\Zahy.Settlement.Application.Contracts.csproj" />
    <ProjectReference Include="..\..\Zahy.Commission\Zahy.Commission.Application\Zahy.Commission.Application.csproj" />
    <ProjectReference Include="..\..\Zahy.Commission\Zahy.Commission.Application.Contracts\Zahy.Commission.Application.Contracts.csproj" />
  </ItemGroup>
</Project>
