<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Application" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Zahy.OrderLedger.Domain\Zahy.OrderLedger.Domain.csproj" />
    <ProjectReference Include="..\Zahy.OrderLedger.Application.Contracts\Zahy.OrderLedger.Application.Contracts.csproj" />
    <ProjectReference Include="..\..\Zahy.Webhooks\Zahy.Webhooks.Application.Contracts\Zahy.Webhooks.Application.Contracts.csproj" />
  </ItemGroup>
</Project>