<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Application" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Zahy.PartnerPlatform.Domain\Zahy.PartnerPlatform.Domain.csproj" />
    <ProjectReference Include="..\Zahy.PartnerPlatform.Application.Contracts\Zahy.PartnerPlatform.Application.Contracts.csproj" />
  </ItemGroup>
</Project>