<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Volo.Abp.Validation" Version="10.4.1" />
    <PackageVersion Include="Volo.Abp.Ddd.Domain" Version="10.4.1" />
    <PackageVersion Include="Volo.Abp.Ddd.Application" Version="10.4.1" />
    <PackageVersion Include="Volo.Abp.Ddd.Application.Contracts" Version="10.4.1" />
    <PackageVersion Include="Volo.Abp.Authorization" Version="10.4.1" />
    <PackageVersion Include="Volo.Abp.EntityFrameworkCore" Version="10.4.1" />
    <PackageVersion Include="Volo.Abp.EntityFrameworkCore.SqlServer" Version="10.4.1" />
    <PackageVersion Include="Volo.Abp.AspNetCore.Mvc" Version="10.4.1" />
    <PackageVersion Include="Volo.Abp.Autofac" Version="10.4.1" />
  </ItemGroup>
</Project>