<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Volo.Abp.EntityFrameworkCore" />
    <PackageReference Include="Volo.Abp.Identity.EntityFrameworkCore" />
    <PackageReference Include="Volo.Abp.OpenIddict.EntityFrameworkCore" />
    <PackageReference Include="Volo.Abp.PermissionManagement.EntityFrameworkCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Zahy.Identity.Domain\Zahy.Identity.Domain.csproj" />
  </ItemGroup>
</Project>
