import type { jsPDF } from "jspdf";
import type { Receipt } from "@/lib/data/types";
import type { Lang } from "@/lib/i18n";

/**
 * Money cycle — clean proof-of-payment receipt (MOCK / BETA, flagged off).
 *
 * NOTE on language: jsPDF's built-in fonts are WinAnsi-encoded and cannot shape
 * connected Arabic script. To keep the generated PDF always legible we render the
 * receipt body with English labels + Western data, and surface the Arabic context
 * (title, "paid by") as a secondary line where it is safe to do so. The surrounding
 * UI (buttons, toasts, on-screen receipt) is fully bilingual. Embedding an Arabic
 * font + bidi shaper is the documented next step for a production tax-grade receipt.
 */

const BRAND = "#0f766e";

const METHOD_LABEL: Record<Receipt["method"], string> = {
  COD: "Cash on Delivery",
  Online: "Online",
  Transfer: "Bank Transfer",
};

function fmtMoney(amount: number, currency: string): string {
  return `${currency} ${amount.toLocaleString("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}

function fmtDate(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toISOString().slice(0, 10);
}

async function buildReceiptDoc(receipt: Receipt, _lang: Lang = "en"): Promise<jsPDF> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const left = 56;
  const right = pageW - 56;

  // ---- Header band ----
  doc.setFillColor(BRAND);
  doc.rect(0, 0, pageW, 96, "F");
  doc.setTextColor("#ffffff");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(26);
  doc.text("ZAHY", left, 50);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text("Partner Platform", left, 70);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("PAYMENT RECEIPT", right, 50, { align: "right" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text("إيصال سداد", right, 70, { align: "right" });

  // ---- BETA / not-a-tax-invoice watermark ----
  doc.setTextColor("#e2e8f0");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(66);
  doc.text("BETA", pageW / 2, 430, { align: "center", angle: 22 });
  doc.setTextColor("#94a3b8");
  doc.setFontSize(11);
  doc.text("BETA — proof of payment, not a ZATCA tax invoice", pageW / 2, 470, {
    align: "center",
  });

  // ---- Meta block ----
  let y = 150;
  doc.setTextColor("#0f172a");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(`Receipt No: ${receipt.receiptNo}`, left, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor("#475569");
  doc.text(`Date: ${fmtDate(receipt.date)}`, right, y, { align: "right" });

  // ---- Detail rows ----
  y += 36;
  const rows: Array<[string, string]> = [
    ["Paid by (Merchant)", receipt.merchantName],
    ["Invoice reference", receipt.invoiceRef],
    ["Payment method", METHOD_LABEL[receipt.method]],
    ["Amount received", fmtMoney(receipt.amount.amount, receipt.amount.currency)],
  ];

  doc.setDrawColor("#e2e8f0");
  for (const [label, value] of rows) {
    doc.setTextColor("#64748b");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.text(label, left, y);
    doc.setTextColor("#0f172a");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text(value, right, y, { align: "right" });
    y += 14;
    doc.line(left, y, right, y);
    y += 22;
  }

  // ---- Amount emphasis ----
  y += 10;
  doc.setFillColor("#f1f5f9");
  doc.roundedRect(left, y, right - left, 56, 6, 6, "F");
  doc.setTextColor("#0f172a");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text("Total received", left + 16, y + 24);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(BRAND);
  doc.text(fmtMoney(receipt.amount.amount, receipt.amount.currency), right - 16, y + 36, {
    align: "right",
  });

  // ---- Footer ----
  doc.setTextColor("#94a3b8");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(
    "Generated by Zahy Partner Platform (mock). Computer-generated — no signature required.",
    pageW / 2,
    doc.internal.pageSize.getHeight() - 48,
    { align: "center" },
  );

  return doc;
}

/** Build the receipt and trigger a browser download (jsPDF is lazy-loaded). */
export async function downloadReceiptPdf(receipt: Receipt, lang: Lang = "en"): Promise<void> {
  const doc = await buildReceiptDoc(receipt, lang);
  doc.save(`${receipt.receiptNo}.pdf`);
}
